interval = '4h'
target = '~/.cache/fzf'
log = '~/.cache/fzf.log'

dirs = [
  '$HOME/dev',
  '/mnt/passport/Series',
  '/mnt/passport/Movies',
]

ignore = [
  'build',
  'bin',
  'node_modules',
  '.git',
  '.idea',
  '.gradle',
  '.DS_Store',
]

[cache]
  enabled = true
  dir = '$HOME/.cache/fzf'