name: Cross Compile releases 

on:
  push:
    branches: [ main, cicd ]

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: >
      vutils-${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # - host: ubuntu-latest
            # target: x86_64-unknown-linux-musl
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Bootstrap V
        run: ./build-scripts/bootstrap-v.sh
        shell: bash
      
      # - name: Release ${{ matrix.settings.target }}
        # uses: actions/upload-artifact@v4

