name: Cross Compile releases 

on:
  push:
    tags: [ '*' ]

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: >
      vutils-${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # - host: ubuntu-latest
            # target: x86_64-unknown-linux-musl
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build-scripts/bootstrap-v.sh
        shell: bash
      
      # - name: CreateRelease
      #   id: create_release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body_path: chanelog.md
      
      - name: UploadArtifacts ${{ matrix.settings.target }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: vutils-${{ matrix.settings.target }}
          asset_path: bin.tar.gz
          asset_content_type: application/gzip
